export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
export const GET_ONE_BRAND = "GET_ONE_BRAND";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const VIEW_ALL_REVIEWS_PRODUCT = "VIEW_ALL_REVIEWS_PRODUCT";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const UPDATE_REVIEW = "UPDATE_REVIEW";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST";

export const LOGIN_USER = "LOGIN_USER";
export const EDIT_USER_DATA = "EDIT_USER_DATA";
export const EDIT_USER_PASSWORD = "EDIT_USER_PASSWORD";

export const GET_ERROR = "GET_ERROR";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const ADD_COUPON = "ADD_COUPON";
export const EDIT_COUPON = "EDIT_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const ONE_COUPON = "ONE_COUPON";

export const GET_ALL_COUPONS = "GET_ALL_COUPONS";
export const GET_ALL_ADDRESSESS = "GET_ALL_ADDRESSESS";
export const GET_ONE_ADDRESS = "GET_ONE_ADDRESS";

export const ADD_ADRESS = "ADD_ADRESS";
export const UPDATE_ADRESS = "UPDATE_ADRESS";
export const DELETE_ADRESS = "DELETE_ADRESS";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const GET_All_PRODUCTS_BY_CATEGORY = "GET_All_PRODUCTS_BY_CATEGORY";
export const GET_All_PRODUCTS_BY_BRAND = "GET_All_PRODUCTS_BY_BRAND";
export const ADD_TO_CART = "ADD_TO_CART"
export const GET_ALL_USER_CART = "GET_ALL_USER_CART"
export const CLEAR_ALL_USER_CART = "CLEAR_ALL_USER_CART"
export const UPDATE_ITEM_FROMCART = "UPDATE_ITEM_FROMCART"
export const DELETE_ITEM_FROMCART = "DELETE_ITEM_FROMCART"
export const APPALY_COUPON_CART = "APPALY_COUPON_CART"
export const CREATE_CASH_ORDER = "CREATE_CASH_ORDER"
export const CREATE_CARD_ORDER = "CREATE_CARD_ORDER"

export const GET_ALL_USER_ORDERS = "GET_ALL_USER_ORDERS"
export const GET_ONE_ORDER = "GET_ONE_ORDER"
export const TYPE_ORDER_PAID = "TYPE_ORDER_PAID"
export const TYPE_ORDER_DELIVERD = "TYPE_ORDER_DELIVERD"






